NodeVersion = "2".

%bunch(node,
%    Version = NodeVersion ++ "2",
%    Check = "mise current node | grep ~Version~",
%    runtime(mise, Version),
%    check(Check),
%    steps([
%        run("npm install -g pnpm"),
%        run("npm install -g typescript")
%    ])
%).

bunch(agent,
    AgentVersion = NodeVersion ++ "1",
    runtime(shell),
    steps([
        run("echo ~AgentVersion~"),
    ])
).

bunch(agent2,
    Agent2Version = NodeVersion ++ "2",
    runtime(shell),
    steps([
        run("echo ~Agent2Version~"),
    ])
).

bunch(agent3,
    Agent3Version = NodeVersion ++ "3",
    depends([agent2, agent]),
    runtime(shell),
    steps([
        run("echo ~Agent3Version~"),
    ])
).

% SSH Generate
SshDir    = "$HOME/.ssh".
KeyFile   = "$HOME/.ssh/id_rsa".

bunch(ssh_keygen,
    runtime(shell),
    check("test -f ~KeyFile~"),
    steps([
        pre("mkdir -p ~SshDir~ && chmod 755 ~SshDir~"),
        run("ssh-keygen -t rsa -b 4096 -f ~KeyFile~ -N \"\"")
    ])
).

bunch(ssh_install,
    runtime(shell),
    depends([ssh_keygen]),
    check("grep -qxFf ~KeyFile~.pub ~SshDir~/authorized_keys 2>/dev/null"),
    steps([
        run("cat ~KeyFile~.pub >> ~SshDir~/authorized_keys")
    ])
).