NodeVersion = "22".
CheckCmd = "mise current node | grep ~NodeVersion~".

bunch(node,
    runtime(mise, NodeVersion),
    check(CheckCmd),
    steps([
        run("npm install -g pnpm"),
        run("npm install -g typescript")
    ])
).
