NodeVersion = "2".

bunch(node,
    Version = NodeVersion ++ "2",
    Check = "mise current node | grep ~Version~",
    runtime(mise, Version),
    check(Check),
    steps([
        run("npm install -g pnpm"),
        run("npm install -g typescript")
    ])
).
