package visitor_test

import (
	"strings"
	"testing"

	"github.com/ppp3ppj/bnn/ast"
	"github.com/ppp3ppj/bnn/visitor"
)

func export(t *testing.T, m *ast.ManifestNode) string {
	t.Helper()
	var sb strings.Builder
	if err := visitor.Export(m, &sb); err != nil {
		t.Fatalf("Export error: %v", err)
	}
	return sb.String()
}

// --- header ---

func TestExport_header(t *testing.T) {
	m := manifest(bunch("ruby", ast.RuntimeShell, nil, "", run("gem install bundler")))
	out := export(t, m)
	assertContains(t, out, "#!/usr/bin/env bash")
	assertContains(t, out, "set -euo pipefail")
	assertContains(t, out, "# Generated by bnn export")
}

// --- bunch header ---

func TestExport_bunchHeader(t *testing.T) {
	m := manifest(bunch("ruby", ast.RuntimeShell, nil, "", run("gem install bundler")))
	out := export(t, m)
	assertContains(t, out, "# --- bunch: ruby ---")
}

// --- runtime: shell ---

func TestExport_shell_noRuntimeLine(t *testing.T) {
	m := manifest(bunch("setup", ast.RuntimeShell, nil, "", run("echo hello")))
	out := export(t, m)
	assertNotContains(t, out, "mise")
	assertNotContains(t, out, "brew")
	assertContains(t, out, "echo hello")
}

// --- runtime: mise ---

func TestExport_mise_installAndGlobal(t *testing.T) {
	m := manifest(manifest_bunch_mise("ruby", "3.3"))
	out := export(t, m)
	assertContains(t, out, "mise install ruby@3.3")
	assertContains(t, out, "mise global ruby@3.3")
}

// --- runtime: brew ---

func TestExport_brew(t *testing.T) {
	m := manifest(bunch("curl", ast.RuntimeBrew, nil, "", run("curl --version")))
	out := export(t, m)
	assertContains(t, out, "brew install curl")
}

// --- check wraps body in if/else/fi ---

func TestExport_check_wrapsInIfElse(t *testing.T) {
	m := manifest(bunch("ruby", ast.RuntimeShell, nil, "command -v ruby", run("echo install ruby")))
	out := export(t, m)
	assertContains(t, out, "if command -v ruby 2>/dev/null; then")
	assertContains(t, out, "already configured, skipping")
	assertContains(t, out, "else")
	assertContains(t, out, "  echo install ruby")
	assertContains(t, out, "fi")
}

func TestExport_noCheck_noIfBlock(t *testing.T) {
	m := manifest(bunch("ruby", ast.RuntimeShell, nil, "", run("echo install ruby")))
	out := export(t, m)
	assertNotContains(t, out, "if ")
	assertNotContains(t, out, "fi")
	assertContains(t, out, "echo install ruby")
}

// --- steps: pre, run, post all emitted ---

func TestExport_stepKinds(t *testing.T) {
	m := manifest(bunch("ruby", ast.RuntimeShell, nil, "",
		pre("echo before"),
		run("gem install bundler"),
		post("echo after"),
	))
	out := export(t, m)
	assertContains(t, out, "echo before")
	assertContains(t, out, "gem install bundler")
	assertContains(t, out, "echo after")
}

// --- depends comment ---

func TestExport_depends_showsComment(t *testing.T) {
	m := manifest(
		bunch("base", ast.RuntimeShell, nil, "", run("echo base")),
		bunch("app", ast.RuntimeShell, []string{"base"}, "", run("echo app")),
	)
	out := export(t, m)
	assertContains(t, out, "# depends: base")
}

func TestExport_noDepends_noComment(t *testing.T) {
	m := manifest(bunch("ruby", ast.RuntimeShell, nil, "", run("echo ruby")))
	out := export(t, m)
	assertNotContains(t, out, "# depends:")
}

// --- dependency order is respected ---

func TestExport_resolvedOrder(t *testing.T) {
	// declared: rails, ruby — rails depends on ruby → ruby must appear first
	m := manifest(
		bunch("rails", ast.RuntimeShell, []string{"ruby"}, "", run("gem install rails")),
		bunch("ruby", ast.RuntimeShell, nil, "", run("echo ruby")),
	)
	out := export(t, m)
	rubyPos := strings.Index(out, "# --- bunch: ruby ---")
	railsPos := strings.Index(out, "# --- bunch: rails ---")
	if rubyPos == -1 || railsPos == -1 {
		t.Fatal("missing bunch headers")
	}
	if rubyPos > railsPos {
		t.Errorf("expected ruby before rails in output")
	}
}

// --- error: circular dependency ---

func TestExport_error_cycle(t *testing.T) {
	m := manifest(
		bunch("a", ast.RuntimeShell, []string{"b"}, "", run("echo a")),
		bunch("b", ast.RuntimeShell, []string{"a"}, "", run("echo b")),
	)
	var sb strings.Builder
	err := visitor.Export(m, &sb)
	if err == nil {
		t.Fatal("expected error for circular dependency")
	}
}

// --- empty manifest ---

func TestExport_emptyManifest(t *testing.T) {
	out := export(t, manifest())
	assertContains(t, out, "#!/usr/bin/env bash")
}

// helper: bunch with mise runtime and version
func manifest_bunch_mise(name, version string) ast.BunchNode {
	return ast.BunchNode{
		Name:    name,
		Runtime: ast.RuntimeNode{Type: ast.RuntimeMise, Version: version},
		Steps:   []ast.StepNode{run("echo done")},
	}
}
