package visitor

import (
	"fmt"
	"io"
	"strings"

	"github.com/ppp3ppj/bnn/ast"
)

// Export writes a self-contained bash script to w that reproduces what
// bnn would execute, in dependency-resolved order.
func Export(m *ast.ManifestNode, w io.Writer) error {
	ordered, err := Resolve(m)
	if err != nil {
		return err
	}

	fmt.Fprintln(w, "#!/usr/bin/env bash")
	fmt.Fprintln(w, "set -euo pipefail")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "# Generated by bnn export")

	for _, b := range ordered {
		fmt.Fprintln(w, "")
		exportBunch(b, w)
	}
	return nil
}

func exportBunch(b ast.BunchNode, w io.Writer) {
	fmt.Fprintf(w, "# --- bunch: %s ---\n", b.Name)

	if len(b.Depends) > 0 {
		fmt.Fprintf(w, "# depends: %s\n", strings.Join(b.Depends, ", "))
	}

	// collect all commands that run inside this bunch
	var body []string

	switch b.Runtime.Type {
	case ast.RuntimeMise:
		ref := b.Name + "@" + b.Runtime.Version
		body = append(body, fmt.Sprintf("mise install %s", ref))
		body = append(body, fmt.Sprintf("mise global %s", ref))
	case ast.RuntimeBrew:
		body = append(body, fmt.Sprintf("brew install %s", b.Name))
	case ast.RuntimeShell:
		// no runtime setup step
	}

	for _, s := range b.Steps {
		body = append(body, s.Command)
	}

	if b.Check != "" {
		fmt.Fprintf(w, "if %s 2>/dev/null; then\n", b.Check)
		fmt.Fprintf(w, "  echo \"[bnn] %s: already configured, skipping\"\n", b.Name)
		fmt.Fprintln(w, "else")
		for _, cmd := range body {
			fmt.Fprintf(w, "  %s\n", cmd)
		}
		fmt.Fprintln(w, "fi")
	} else {
		for _, cmd := range body {
			fmt.Fprintln(w, cmd)
		}
	}
}
